type Catogory = {
  id: string;
  name: string;
  icon: React.ReactNode;
  keywords: string[];
};

export const Categories = {
  TECH: {
    id: "TECH",
    name: "Tech",
    icon: <span aria-hidden="true">👨‍💻</span>,
    keywords: [
      "technology",
      "tech news",
      "tech trends",
      "software",
      "hardware",
      "digital technology",
      "innovation",
      "tech industry",
      "programming",
      "computing",
    ],
  },
  DX: {
    id: "DX",
    name: "Development Experience",
    icon: <span aria-hidden="true">👨‍💻</span>,
    keywords: [
      "developer experience",
      "DX",
      "software development",
      "developer tools",
      "coding experience",
      "development workflow",
      "productivity",
      "developer efficiency",
      "code quality",
      "development best practices",
    ],
  },
  IOT: {
    id: "IOT",
    name: "Internet of Things",
    icon: <span aria-hidden="true">🌐</span>,
    keywords: [
      "Internet of Things",
      "IoT",
      "connected devices",
      "home assistant",
      "smart home",
      "IoT technology",
      "IoT applications",
      "embedded systems",
      "sensors",
      "IoT security",
      "smart devices",
    ],
  },
  EXPLORE: {
    id: "EXPLORE",
    name: "Explore",
    icon: <span aria-hidden="true">🧭</span>,
    keywords: [
      "exploration",
      "discovery",
      "research",
      "innovation",
      "new technologies",
      "emerging tech",
      "tech exploration",
      "experimental",
      "cutting-edge",
      "technology discovery",
    ],
  },
  WATCH: {
    id: "WATCH",
    name: "Watch",
    icon: <span aria-hidden="true">⌚</span>,
    keywords: [
      "smartwatch",
      "wearable technology",
      "wearables",
      "watch tech",
      "fitness trackers",
      "smart wearables",
      "Apple Watch",
      "Galaxy Watch",
      "Samsung Galaxy Watch",
      "Watch",
      "Garmin",
      "Fitbit",
      "wearable devices",
    ],
  },
  FRONT_END: {
    id: "FRONT_END",
    name: "Front-end",
    icon: <span aria-hidden="true">💻</span>,
    keywords: [
      "front-end development",
      "web development",
      "UI design",
      "UX design",
      "JavaScript",
      "CSS",
      "HTML",
      "React",
      "Vue",
      "responsive design",
      "web frameworks",
    ],
  },
  AI: {
    id: "AI",
    name: "Artificial Intelligence",
    icon: <span aria-hidden="true">✨</span>,
    keywords: [
      "artificial intelligence",
      "AI",
      "machine learning",
      "deep learning",
      "neural networks",
      "AI applications",
      "natural language processing",
      "computer vision",
      "AI ethics",
      "generative AI",
    ],
  },
} as const satisfies Record<string, Catogory>;
